In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('01_suitability_scores (1).csv')
df.head()

,plant_id,scientific_name,common_ar,priority,adm1_pcode,gov_en,gov_ar,cycle_months_needed,months_in_range,months_optimal,score_temperature,soil_ph,score_ph,suitability_score,frost_months_below_5c,rain_mm_year,irrigation_need_mm_year,criteria_used,n_criteria,analyst_note
0,P01,Catharanthus roseus,ونكة مدغشقرية,1,EG01,Cairo,القاهرة,6,12,6,1.0,8.0,0.0,0.000000,4,91.259405,908.740595,temperature+pH,2,SEVERELY CONSTRAINED BY ALKALINITY. Absolute p...
1,P01,Catharanthus roseus,ونكة مدغشقرية,1,EG02,Alexandria,الاسكندرية,6,12,7,1.0,7.9,0.0,0.000000,0,124.619167,875.380833,temperature+pH,2,SEVERELY CONSTRAINED BY ALKALINITY. Absolute p...
2,P01,Catharanthus roseus,ونكة مدغشقرية,1,EG03,Port Said,بورسعيد,6,12,7,1.0,7.9,0.0,0.000000,0,100.216548,899.783452,temperature+pH,2,SEVERELY CONSTRAINED BY ALKALINITY. Absolute p...
3,P01,Catharanthus roseus,ونكة مدغشقرية,1,EG04,Suez,السويس,6,12,6,1.0,8.0,0.0,0.000000,4,66.677381,933.322619,temperature+pH,2,SEVERELY CONSTRAINED BY ALKALINITY. Absolute p...
4,P01,Catharanthus roseus,ونكة مدغشقرية,1,EG11,Damietta,دمياط,6,12,7,1.0,7.2,0.6,0.774597,0,123.222857,876.777143,temperature+pH,2,SEVERELY CONSTRAINED BY ALKALINITY. Absolute p...

In [3]:
# 1. إظهار أبعاد الجدول (عدد الصفوف، عدد الأعمدة)
print("جدول البيانات يتكون من:")
print(f"عدد الصفوف: {df.shape[0]}")
print(f"عدد الأعمدة: {df.shape[1]}\n")

# 2. عرض ملخص الشامل للأعمدة وأنواع البيانات
df.info()

جدول البيانات يتكون من:
عدد الصفوف: 594
عدد الأعمدة: 20

<class 'pandas.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   plant_id                 594 non-null    str
 1   scientific_name          594 non-null    str
 2   common_ar                594 non-null    str
 3   priority                 594 non-null    int64
 4   adm1_pcode               594 non-null    str
 5   gov_en                   594 non-null    str
 6   gov_ar                   594 non-null    str
 7   cycle_months_needed      594 non-null    int64
 8   months_in_range          594 non-null    int64
 9   months_optimal           594 non-null    int64
 10  score_temperature        594 non-null    float64
 11  soil_ph                  594 non-null    float64
 12  score_ph                 594 non-null    float64
 13  suitability_score        594 non-null    float64
 14  frost_months_below_5c    594 non-null    int64
 15  rain_mm_year             594 non-null    float64
 16  irrigation_need_mm_year  459 non-null    float64
 17  criteria_used            594 non-null    str
 18  n_criteria               594 non-null    int64
 19  analyst_note             324 non-null    str
dtypes: float64(6), int64(6), str(8)
memory usage: 92.9 KB

In [4]:
# 1. حساب عدد القيم الفارغة في كل عمود
print("--- عدد القيم المفقودة في كل عمود ---")
print(df.isnull().sum())

# 2. حساب عدد الصفوف المكررة
print("\n--- عدد الصفوف المكررة بالكامل ---")
print(f"الصفووف المكررة: {df.duplicated().sum()}")

--- عدد القيم المفقودة في كل عمود ---
plant_id                     0
scientific_name              0
common_ar                    0
priority                     0
adm1_pcode                   0
gov_en                       0
gov_ar                       0
cycle_months_needed          0
months_in_range              0
months_optimal               0
score_temperature            0
soil_ph                      0
score_ph                     0
suitability_score            0
frost_months_below_5c        0
rain_mm_year                 0
irrigation_need_mm_year    135
criteria_used                0
n_criteria                   0
analyst_note               270
dtype: int64

--- عدد الصفوف المكررة بالكامل ---
الصفووف المكررة: 0

In [5]:
# إحصائيات الأعمدة الرقمية (الأرقام)
print("--- إحصائيات الأعمدة الرقمية ---")
display(df.describe())

# إحصائيات الأعمدة النصية
print("--- إحصائيات الأعمدة النصية ---")
display(df.describe(include=['object']))

--- إحصائيات الأعمدة الرقمية ---

,priority,cycle_months_needed,months_in_range,months_optimal,score_temperature,soil_ph,score_ph,suitability_score,frost_months_below_5c,rain_mm_year,irrigation_need_mm_year,n_criteria
count,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,459.000000,594.0
mean,1.909091,4.500000,10.841751,5.469697,0.988777,7.844444,0.512047,0.621813,2.074074,56.295802,672.527727,2.0
std,0.793195,2.312988,1.714498,2.099528,0.059982,0.318053,0.383977,0.351599,1.514818,43.255141,274.560829,0.0
min,1.000000,1.000000,6.000000,0.000000,0.500000,7.100000,0.000000,0.000000,0.000000,1.518333,246.335595,2.0
25%,1.000000,3.000000,10.000000,4.000000,1.000000,7.800000,0.153846,0.392232,1.000000,8.740595,476.777143,2.0
50%,2.000000,4.000000,12.000000,5.000000,1.000000,8.000000,0.444444,0.666667,2.000000,65.812381,597.898333,2.0
75%,3.000000,5.000000,12.000000,7.000000,1.000000,8.100000,1.000000,1.000000,3.000000,85.467619,857.678333,2.0
max,3.000000,12.000000,12.000000,12.000000,1.000000,8.200000,1.000000,1.000000,5.000000,153.664405,1498.481667,2.0

--- إحصائيات الأعمدة النصية ---

C:\Users\A-FF-L1-D12\AppData\Local\Temp\ipykernel_26028\2505018720.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include=['object']))

,plant_id,scientific_name,common_ar,adm1_pcode,gov_en,gov_ar,criteria_used,analyst_note
count,594,594,594,594,594,594,594,324
unique,22,22,22,27,27,27,1,12
top,P01,Catharanthus roseus,ونكة مدغشقرية,EG01,Cairo,القاهرة,temperature+pH,SEVERELY CONSTRAINED BY ALKALINITY. Absolute p...
freq,27,27,27,22,22,22,594,27

In [6]:
# إظهار عدد الصفوف والأعمدة
print("أبعاد البيانات (صفوف، أعمدة):", df.shape)

# عرض تفاصيل الأعمدة وأنواع البيانات
df.info()

أبعاد البيانات (صفوف، أعمدة): (594, 20)
<class 'pandas.DataFrame'>
RangeIndex: 594 entries, 0 to 593
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   plant_id                 594 non-null    str
 1   scientific_name          594 non-null    str
 2   common_ar                594 non-null    str
 3   priority                 594 non-null    int64
 4   adm1_pcode               594 non-null    str
 5   gov_en                   594 non-null    str
 6   gov_ar                   594 non-null    str
 7   cycle_months_needed      594 non-null    int64
 8   months_in_range          594 non-null    int64
 9   months_optimal           594 non-null    int64
 10  score_temperature        594 non-null    float64
 11  soil_ph                  594 non-null    float64
 12  score_ph                 594 non-null    float64
 13  suitability_score        594 non-null    float64
 14  frost_months_below_5c    594 non-null    int64
 15  rain_mm_year             594 non-null    float64
 16  irrigation_need_mm_year  459 non-null    float64
 17  criteria_used            594 non-null    str
 18  n_criteria               594 non-null    int64
 19  analyst_note             324 non-null    str
dtypes: float64(6), int64(6), str(8)
memory usage: 92.9 KB

In [7]:
# حساب القيم المفقودة في كل عمود
print("--- القيم المفقودة (Nulls) ---")
print(df.isnull().sum())

# حساب الصفوف المكررة
print("\nعدد الصفوف المكررة بالكامل:", df.duplicated().sum())

--- القيم المفقودة (Nulls) ---
plant_id                     0
scientific_name              0
common_ar                    0
priority                     0
adm1_pcode                   0
gov_en                       0
gov_ar                       0
cycle_months_needed          0
months_in_range              0
months_optimal               0
score_temperature            0
soil_ph                      0
score_ph                     0
suitability_score            0
frost_months_below_5c        0
rain_mm_year                 0
irrigation_need_mm_year    135
criteria_used                0
n_criteria                   0
analyst_note               270
dtype: int64

عدد الصفوف المكررة بالكامل: 0

In [8]:
# إحصائيات للأعمدة الرقمية والنصية معاً
df.describe(include='all')

,plant_id,scientific_name,common_ar,priority,adm1_pcode,gov_en,gov_ar,cycle_months_needed,months_in_range,months_optimal,score_temperature,soil_ph,score_ph,suitability_score,frost_months_below_5c,rain_mm_year,irrigation_need_mm_year,criteria_used,n_criteria,analyst_note
count,594,594,594,594.000000,594,594,594,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,459.000000,594,594.0,324
unique,22,22,22,NaN,27,27,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,12
top,P01,Catharanthus roseus,ونكة مدغشقرية,NaN,EG01,Cairo,القاهرة,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,temperature+pH,NaN,SEVERELY CONSTRAINED BY ALKALINITY. Absolute p...
freq,27,27,27,NaN,22,22,22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,594,NaN,27
mean,NaN,NaN,NaN,1.909091,NaN,NaN,NaN,4.500000,10.841751,5.469697,0.988777,7.844444,0.512047,0.621813,2.074074,56.295802,672.527727,NaN,2.0,NaN
std,NaN,NaN,NaN,0.793195,NaN,NaN,NaN,2.312988,1.714498,2.099528,0.059982,0.318053,0.383977,0.351599,1.514818,43.255141,274.560829,NaN,0.0,NaN
min,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,1.000000,6.000000,0.000000,0.500000,7.100000,0.000000,0.000000,0.000000,1.518333,246.335595,NaN,2.0,NaN
25%,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,3.000000,10.000000,4.000000,1.000000,7.800000,0.153846,0.392232,1.000000,8.740595,476.777143,NaN,2.0,NaN
50%,NaN,NaN,NaN,2.000000,NaN,NaN,NaN,4.000000,12.000000,5.000000,1.000000,8.000000,0.444444,0.666667,2.000000,65.812381,597.898333,NaN,2.0,NaN
75%,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,5.000000,12.000000,7.000000,1.000000,8.100000,1.000000,1.000000,3.000000,85.467619,857.678333,NaN,2.0,NaN
max,NaN,NaN,NaN,3.000000,NaN,NaN,NaN,12.000000,12.000000,12.000000,1.000000,8.200000,1.000000,1.000000,5.000000,153.664405,1498.481667,NaN,2.0,NaN

In [9]:
# 1. تعبئة القيم المفقودة في احتِياج الري بمتوسط العمود
df['irrigation_need_mm_year'] = df['irrigation_need_mm_year'].fillna(df['irrigation_need_mm_year'].mean())

# 2. تعبئة الملاحظات المفقودة بنص واضح
df['analyst_note'] = df['analyst_note'].fillna('No Note')

# التأكد من معالجة جميع القيم المفقودة
print("عدد القيم المفقودة بعد التنظيف:")
print(df[['irrigation_need_mm_year', 'analyst_note']].isnull().sum())

عدد القيم المفقودة بعد التنظيف:
irrigation_need_mm_year    0
analyst_note               0
dtype: int64

In [10]:
# إظهار أنواع البيانات بعد التنظيف
df.dtypes

plant_id                       str
scientific_name                str
common_ar                      str
priority                     int64
adm1_pcode                     str
gov_en                         str
gov_ar                         str
cycle_months_needed          int64
months_in_range              int64
months_optimal               int64
score_temperature          float64
soil_ph                    float64
score_ph                   float64
suitability_score          float64
frost_months_below_5c        int64
rain_mm_year               float64
irrigation_need_mm_year    float64
criteria_used                  str
n_criteria                   int64
analyst_note                   str
dtype: object

In [11]:
# حفظ الملف المنظف بنفس المجلد
df.to_csv('01_suitability_scores_cleaned.csv', index=False)
print("تم حفظ الملف المنظف بنجاح باسم: 01_suitability_scores_cleaned.csv")

تم حفظ الملف المنظف بنجاح باسم: 01_suitability_scores_cleaned.csv

In [12]:
# حساب متوسط درجة الملاءمة لكل نبات
top_plants = df.groupby('common_ar')['suitability_score'].mean().sort_values(ascending=False).head(10)

print("--- أعلى 10 نباتات ملاءمةً ---")
print(top_plants)

--- أعلى 10 نباتات ملاءمةً ---
common_ar
ست الحسن             1.000000
الشيح الحولي         0.968191
داتورة               0.968191
خلة بلدي             0.943568
عنب الديب            0.939634
خلة شيطاني           0.879089
سكران مصري           0.814815
شوك الجمل / خرفيش    0.797151
صبار / الوة          0.765747
خشخاش منوم           0.686941
Name: suitability_score, dtype: float64

In [13]:
# حساب متوسط الملاءمة لكل محافظة
top_govs = df.groupby('gov_ar')['suitability_score'].mean().sort_values(ascending=False)

print("--- ترتيب المحافظات حسب متوسط الملاءمة ---")
print(top_govs)

--- ترتيب المحافظات حسب متوسط الملاءمة ---
gov_ar
كفر الشيخ        0.880150
الدقهلية         0.874060
دمياط            0.861836
القليوبية        0.828118
الشرقية          0.809717
الغربية          0.704636
البحيرة          0.704636
الفيوم           0.703510
شمال سيناء       0.649962
الاسكندرية       0.649277
بورسعيد          0.648561
المنوفية         0.647809
الجيزة           0.647809
مطروح            0.558674
البحر الأحمر     0.558674
الإسماعيلية      0.558674
جنوب سيناء       0.558674
السويس           0.558674
القاهرة          0.558674
بنى سويف         0.558674
أسيوط            0.483630
أسوان            0.483630
المنيا           0.483630
قنا              0.483630
سوهاج            0.483630
مدينة الأقصر     0.483630
الوادى الجديد    0.366387
Name: suitability_score, dtype: float64

In [14]:
# أكثر النباتات احتياجاً للمياه
water_needy = df.groupby('common_ar')['irrigation_need_mm_year'].mean().sort_values(ascending=False).head(5)

print("--- أكثر 5 نباتات احتياجاً للري (مم/سنة) ---")
print(water_needy)

--- أكثر 5 نباتات احتياجاً للري (مم/سنة) ---
common_ar
حشيشة الليمون    1443.704198
نعناع فلفلي       943.704198
ونكة مدغشقرية     943.704198
صبار / الوة       943.704198
ونكة صغرى         833.704198
Name: irrigation_need_mm_year, dtype: float64

In [15]:
df.to_csv('01_suitability_scores_cleaned.csv', index=False)