 Read data

In [1]:
import pandas as pd
import numpy as np
import zipfile

Read data from ZIP file

In [2]:
zip_path = r"C:\Users\A-FF-L1-D06\Desktop\ملف المشروع\02_Soil_التربة-20260825T061412Z-1-001.zip"

file_inside_zip = "02_Soil_التربة/01_soil_properties_by_governorate.csv"

with zipfile.ZipFile(zip_path, 'r') as z:
    df = pd.read_csv(
        z.open(file_inside_zip),
        encoding="utf-8-sig"
    )

print("Data loaded successfully ")

Data loaded successfully

2. Check data size

In [3]:
print("\nShape:")
print(df.shape)

Shape:
(27, 12)

3. Check columns

In [4]:
print("\nColumns:")
print(df.columns.tolist())

Columns:
['adm1_pcode', 'gov_en', 'gov_ar', 'bdod', 'cec', 'cfvo', 'clay', 'nitrogen', 'phh2o', 'sand', 'silt', 'soc']

 4. Check data types

In [5]:
print("\nData Types:")
print(df.dtypes)

Data Types:
adm1_pcode        str
gov_en            str
gov_ar            str
bdod          float64
cec           float64
cfvo          float64
clay          float64
nitrogen      float64
phh2o         float64
sand          float64
silt          float64
soc           float64
dtype: object

5. Check missing values

In [6]:
print("\nMissing Values:")
print(df.isna().sum())

Missing Values:
adm1_pcode    0
gov_en        0
gov_ar        0
bdod          0
cec           0
cfvo          0
clay          0
nitrogen      0
phh2o         0
sand          0
silt          0
soc           0
dtype: int64

 6. Check zero values

In [7]:

numeric_cols = df.select_dtypes(include=np.number).columns

print("\nZero Values:")
print((df[numeric_cols] == 0).sum())

Zero Values:
bdod        0
cec         0
cfvo        0
clay        0
nitrogen    0
phh2o       0
sand        0
silt        0
soc         0
dtype: int64

7. Check duplicate rows

In [8]:
print("\nDuplicate Rows:")
print(df.duplicated().sum())

Duplicate Rows:
0

 8. Check duplicate governorate codes

In [9]:
if 'adm1_pcode' in df.columns:
    print("\nDuplicate Governorate Codes:")
    print(df['adm1_pcode'].duplicated().sum())

Duplicate Governorate Codes:
0

 9. Check number of governorates

In [10]:
if 'gov_en' in df.columns:
    print("\nNumber of Governorates:")
    print(df['gov_en'].nunique())

Number of Governorates:
27

10. Statistical summary

In [11]:
print("\nStatistics:")
print(df.describe(include='all'))

Statistics:
       adm1_pcode gov_en   gov_ar       bdod        cec       cfvo       clay  \
count          27     27       27  27.000000  27.000000  27.000000  27.000000
unique         27     27       27        NaN        NaN        NaN        NaN
top          EG01  Cairo  القاهرة        NaN        NaN        NaN        NaN
freq            1      1        1        NaN        NaN        NaN        NaN
mean          NaN    NaN      NaN   1.350000  17.566667  18.422222  27.870370
std           NaN    NaN      NaN   0.045064   2.942918  10.537966   5.704035
min           NaN    NaN      NaN   1.260000  13.900000   5.100000  15.700000
25%           NaN    NaN      NaN   1.325000  15.050000   7.150000  26.300000
50%           NaN    NaN      NaN   1.340000  16.900000  18.600000  28.900000
75%           NaN    NaN      NaN   1.385000  19.750000  26.950000  29.950000
max           NaN    NaN      NaN   1.430000  24.600000  36.100000  38.200000

         nitrogen      phh2o       sand       silt        soc
count   27.000000  27.000000  27.000000  27.000000  27.000000
unique        NaN        NaN        NaN        NaN        NaN
top           NaN        NaN        NaN        NaN        NaN
freq          NaN        NaN        NaN        NaN        NaN
mean     1.582593   7.844444  44.248148  27.885185  17.837037
std      1.102007   0.323839   8.927459   5.832383  19.992886
min      0.340000   7.100000  28.900000  13.800000   2.900000
25%      0.800000   7.800000  36.800000  24.800000   4.050000
50%      1.160000   8.000000  42.400000  27.900000   5.600000
75%      2.175000   8.050000  52.050000  31.600000  22.300000
max      4.150000   8.200000  60.100000  41.000000  70.000000

 11. Check negative values

In [12]:
print("\nNegative Values:")
print((df[numeric_cols] < 0).sum())

Negative Values:
bdod        0
cec         0
cfvo        0
clay        0
nitrogen    0
phh2o       0
sand        0
silt        0
soc         0
dtype: int64

12. Check unique values for important columns

In [13]:
print("\nUnique Values:")
for col in df.columns:
    print(f"\n{col}:")
    print(df[col].unique()[:10])

Unique Values:

adm1_pcode:
<StringArray>
['EG01', 'EG02', 'EG03', 'EG04', 'EG11', 'EG12', 'EG13', 'EG14', 'EG15',
 'EG16']
Length: 10, dtype: str

gov_en:
<StringArray>
[        'Cairo',    'Alexandria',     'Port Said',          'Suez',
      'Damietta',      'Dakahlia',       'Sharkia',     'Kalyoubia',
 'Kafr El-Shikh',       'Gharbia']
Length: 10, dtype: str

gov_ar:
<StringArray>
[   'القاهرة', 'الاسكندرية',    'بورسعيد',     'السويس',      'دمياط',
   'الدقهلية',    'الشرقية',  'القليوبية',  'كفر الشيخ',    'الغربية']
Length: 10, dtype: str

bdod:
[1.41 1.38 1.42 1.39 1.31 1.3  1.33 1.28 1.4  1.35]

cec:
[15.  16.8 16.9 14.8 24.6 20.3 20.6 17.8 20.4 19.3]

cfvo:
[31.1  7.7 10.8 13.4  5.1  5.9  6.1  9.9  6.   6.2]

clay:
[29.8 24.4 32.3 29.4 33.3 36.4 29.7 28.9 38.2 30.8]

nitrogen:
[0.45 1.64 1.56 0.96 3.73 3.42 2.78 3.44 4.15 2.69]

phh2o:
[8.  7.9 7.2 7.1 7.4 7.3 7.8 8.1 8.2]

sand:
[41.1 45.  33.9 40.5 35.4 36.6 37.9 42.4 37.  36. ]

silt:
[29.1 30.6 33.8 30.1 31.3 26.9 32.4 27.9 34.1 25.8]

soc:
[ 3.6 17.9 18.   4.4 70.  51.9 35.6 46.  64.8 36. ]

13. Check completely empty columns

In [14]:
empty_cols = df.columns[df.isna().all()].tolist()

print("\nCompletely Empty Columns:")
print(empty_cols)

Completely Empty Columns:
[]

14. Check rows with all values empty

In [15]:
empty_rows = df.isna().all(axis=1).sum()

print("\nCompletely Empty Rows:")
print(empty_rows)

Completely Empty Rows:
0

In [16]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(df.columns)

Index(['adm1_pcode', 'gov_en', 'gov_ar', 'bdod', 'cec', 'cfvo', 'clay',
       'nitrogen', 'phh2o', 'sand', 'silt', 'soc'],
      dtype='str')

In [17]:
text_cols = df.select_dtypes(include="object").columns

for col in text_cols:
    df[col] = df[col].astype(str).str.strip()

C:\Users\A-FF-L1-D06\AppData\Local\Temp\ipykernel_10400\1718341756.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df.select_dtypes(include="object").columns

In [18]:
print(df.dtypes)

adm1_pcode        str
gov_en            str
gov_ar            str
bdod          float64
cec           float64
cfvo          float64
clay          float64
nitrogen      float64
phh2o         float64
sand          float64
silt          float64
soc           float64
dtype: object

In [19]:
for col in numeric_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [20]:
print("\nMissing Values After Cleaning:")
print(df.isna().sum())

Missing Values After Cleaning:
adm1_pcode    0
gov_en        0
gov_ar        0
bdod          0
cec           0
cfvo          0
clay          0
nitrogen      0
phh2o         0
sand          0
silt          0
soc           0
dtype: int64

In [21]:
output_path = r"C:\Users\A-FF-L1-D06\Desktop\ملف المشروع\Soil_Cleaned.csv"

df.to_csv(output_path, index=False, encoding="utf-8-sig")

print("Cleaned file saved successfully ")
print(output_path)

Cleaned file saved successfully
C:\Users\A-FF-L1-D06\Desktop\ملف المشروع\Soil_Cleaned.csv

In [22]:
print("Final Shape:", df.shape)
print("\nFinal Data:")
display(df.head())

Final Shape: (27, 12)

Final Data:

,adm1_pcode,gov_en,gov_ar,bdod,cec,cfvo,clay,nitrogen,phh2o,sand,silt,soc
0,EG01,Cairo,القاهرة,1.41,15.0,31.1,29.8,0.45,8.0,41.1,29.1,3.6
1,EG02,Alexandria,الاسكندرية,1.38,16.8,7.7,24.4,1.64,7.9,45.0,30.6,17.9
2,EG03,Port Said,بورسعيد,1.42,16.9,10.8,32.3,1.56,7.9,33.9,33.8,18.0
3,EG04,Suez,السويس,1.39,14.8,13.4,29.4,0.96,8.0,40.5,30.1,4.4
4,EG11,Damietta,دمياط,1.31,24.6,5.1,33.3,3.73,7.2,35.4,31.3,70.0

In [23]:
display(df.head())

,adm1_pcode,gov_en,gov_ar,bdod,cec,cfvo,clay,nitrogen,phh2o,sand,silt,soc
0,EG01,Cairo,القاهرة,1.41,15.0,31.1,29.8,0.45,8.0,41.1,29.1,3.6
1,EG02,Alexandria,الاسكندرية,1.38,16.8,7.7,24.4,1.64,7.9,45.0,30.6,17.9
2,EG03,Port Said,بورسعيد,1.42,16.9,10.8,32.3,1.56,7.9,33.9,33.8,18.0
3,EG04,Suez,السويس,1.39,14.8,13.4,29.4,0.96,8.0,40.5,30.1,4.4
4,EG11,Damietta,دمياط,1.31,24.6,5.1,33.3,3.73,7.2,35.4,31.3,70.0

In [24]:
display(df)

,adm1_pcode,gov_en,gov_ar,bdod,cec,cfvo,clay,nitrogen,phh2o,sand,silt,soc
0,EG01,Cairo,القاهرة,1.41,15.0,31.1,29.8,0.45,8.0,41.1,29.1,3.6
1,EG02,Alexandria,الاسكندرية,1.38,16.8,7.7,24.4,1.64,7.9,45.0,30.6,17.9
2,EG03,Port Said,بورسعيد,1.42,16.9,10.8,32.3,1.56,7.9,33.9,33.8,18.0
3,EG04,Suez,السويس,1.39,14.8,13.4,29.4,0.96,8.0,40.5,30.1,4.4
4,EG11,Damietta,دمياط,1.31,24.6,5.1,33.3,3.73,7.2,35.4,31.3,70.0
5,EG12,Dakahlia,الدقهلية,1.30,20.3,5.9,36.4,3.42,7.1,36.6,26.9,51.9
6,EG13,Sharkia,الشرقية,1.33,20.6,6.1,29.7,2.78,7.4,37.9,32.4,35.6
7,EG14,Kalyoubia,القليوبية,1.33,17.8,9.9,29.7,3.44,7.3,42.4,27.9,46.0
8,EG15,Kafr El-Shikh,كفر الشيخ,1.33,20.4,6.0,28.9,4.15,7.1,37.0,34.1,64.8
9,EG16,Gharbia,الغربية,1.28,19.3,6.2,38.2,2.69,7.8,36.0,25.8,36.0
10,EG17,Menoufia,المنوفية,1.38,17.8,6.3,30.8,1.67,7.9,44.3,25.0,16.3
11,EG18,Behera,البحيرة,1.40,16.1,6.6,27.6,1.97,7.8,40.5,31.9,17.1
12,EG19,Ismailia,الإسماعيلية,1.41,15.1,18.6,35.5,0.90,8.0,32.5,31.9,5.4
13,EG21,Giza,الجيزة,1.35,14.4,22.5,29.8,0.89,7.9,56.5,13.8,4.2
14,EG22,Beni Suef,بنى سويف,1.32,16.0,26.9,28.0,1.08,8.0,52.3,19.7,5.8
15,EG23,Fayoum,الفيوم,1.26,20.8,12.6,26.0,2.38,7.8,51.8,22.2,26.5
16,EG24,Menia,المنيا,1.33,14.2,21.3,28.6,1.03,8.1,53.7,17.7,3.9
17,EG25,Assiut,أسيوط,1.33,14.5,27.0,28.2,0.59,8.1,44.3,27.5,3.7
18,EG26,Suhag,سوهاج,1.36,15.0,26.4,24.5,0.58,8.1,50.9,24.6,4.9
19,EG27,Qena,قنا,1.34,20.0,22.7,16.2,0.88,8.1,56.4,27.4,3.4
20,EG28,Aswan,أسوان,1.34,24.3,34.7,15.7,1.19,8.1,55.5,28.8,4.1
21,EG29,Luxor,مدينة الأقصر,1.31,17.2,29.5,19.7,1.16,8.1,58.8,21.5,3.2
22,EG31,Red Sea,البحر الأحمر,1.37,16.4,36.1,28.0,0.68,8.0,41.1,31.0,4.3
23,EG32,New Valley,الوادى الجديد,1.35,17.0,34.5,15.8,0.72,8.2,60.1,24.1,2.9
24,EG33,Matrouh,مطروح,1.29,19.5,18.2,26.6,1.18,8.0,46.7,26.7,18.1
25,EG34,North Sinai,شمال سيناء,1.43,13.9,21.8,29.3,0.34,7.9,34.6,36.1,5.6
26,EG35,South Sinai,جنوب سيناء,1.40,15.6,29.5,30.1,0.67,8.0,28.9,41.0,4.0

In [25]:
print(df.columns.tolist())

['adm1_pcode', 'gov_en', 'gov_ar', 'bdod', 'cec', 'cfvo', 'clay', 'nitrogen', 'phh2o', 'sand', 'silt', 'soc']

In [26]:
print(df.columns.tolist())
display(df.head(10))

['adm1_pcode', 'gov_en', 'gov_ar', 'bdod', 'cec', 'cfvo', 'clay', 'nitrogen', 'phh2o', 'sand', 'silt', 'soc']

,adm1_pcode,gov_en,gov_ar,bdod,cec,cfvo,clay,nitrogen,phh2o,sand,silt,soc
0,EG01,Cairo,القاهرة,1.41,15.0,31.1,29.8,0.45,8.0,41.1,29.1,3.6
1,EG02,Alexandria,الاسكندرية,1.38,16.8,7.7,24.4,1.64,7.9,45.0,30.6,17.9
2,EG03,Port Said,بورسعيد,1.42,16.9,10.8,32.3,1.56,7.9,33.9,33.8,18.0
3,EG04,Suez,السويس,1.39,14.8,13.4,29.4,0.96,8.0,40.5,30.1,4.4
4,EG11,Damietta,دمياط,1.31,24.6,5.1,33.3,3.73,7.2,35.4,31.3,70.0
5,EG12,Dakahlia,الدقهلية,1.30,20.3,5.9,36.4,3.42,7.1,36.6,26.9,51.9
6,EG13,Sharkia,الشرقية,1.33,20.6,6.1,29.7,2.78,7.4,37.9,32.4,35.6
7,EG14,Kalyoubia,القليوبية,1.33,17.8,9.9,29.7,3.44,7.3,42.4,27.9,46.0
8,EG15,Kafr El-Shikh,كفر الشيخ,1.33,20.4,6.0,28.9,4.15,7.1,37.0,34.1,64.8
9,EG16,Gharbia,الغربية,1.28,19.3,6.2,38.2,2.69,7.8,36.0,25.8,36.0

In [27]:
print(df.columns.tolist())
display(df.head(10))
print(df.dtypes)
print(df.isnull().sum())

['adm1_pcode', 'gov_en', 'gov_ar', 'bdod', 'cec', 'cfvo', 'clay', 'nitrogen', 'phh2o', 'sand', 'silt', 'soc']

,adm1_pcode,gov_en,gov_ar,bdod,cec,cfvo,clay,nitrogen,phh2o,sand,silt,soc
0,EG01,Cairo,القاهرة,1.41,15.0,31.1,29.8,0.45,8.0,41.1,29.1,3.6
1,EG02,Alexandria,الاسكندرية,1.38,16.8,7.7,24.4,1.64,7.9,45.0,30.6,17.9
2,EG03,Port Said,بورسعيد,1.42,16.9,10.8,32.3,1.56,7.9,33.9,33.8,18.0
3,EG04,Suez,السويس,1.39,14.8,13.4,29.4,0.96,8.0,40.5,30.1,4.4
4,EG11,Damietta,دمياط,1.31,24.6,5.1,33.3,3.73,7.2,35.4,31.3,70.0
5,EG12,Dakahlia,الدقهلية,1.30,20.3,5.9,36.4,3.42,7.1,36.6,26.9,51.9
6,EG13,Sharkia,الشرقية,1.33,20.6,6.1,29.7,2.78,7.4,37.9,32.4,35.6
7,EG14,Kalyoubia,القليوبية,1.33,17.8,9.9,29.7,3.44,7.3,42.4,27.9,46.0
8,EG15,Kafr El-Shikh,كفر الشيخ,1.33,20.4,6.0,28.9,4.15,7.1,37.0,34.1,64.8
9,EG16,Gharbia,الغربية,1.28,19.3,6.2,38.2,2.69,7.8,36.0,25.8,36.0

adm1_pcode        str
gov_en            str
gov_ar            str
bdod          float64
cec           float64
cfvo          float64
clay          float64
nitrogen      float64
phh2o         float64
sand          float64
silt          float64
soc           float64
dtype: object
adm1_pcode    0
gov_en        0
gov_ar        0
bdod          0
cec           0
cfvo          0
clay          0
nitrogen      0
phh2o         0
sand          0
silt          0
soc           0
dtype: int64

In [65]:
output_path = r"C:\Users\A-FF-L1-D06\Desktop\ملف المشروع\Soil_Cleaned.csv"

df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Soil_Cleaned.csv saved successfully ")

Soil_Cleaned.csv saved successfully

In [66]:
print("Final Shape:", df.shape)
display(df.head(10))

Final Shape: (27, 12)

,adm1_pcode,gov_en,gov_ar,bdod,cec,cfvo,clay,nitrogen,phh2o,sand,silt,soc
0,EG01,Cairo,القاهرة,1.41,15.0,31.1,29.8,0.45,8.0,41.1,29.1,3.6
1,EG02,Alexandria,الاسكندرية,1.38,16.8,7.7,24.4,1.64,7.9,45.0,30.6,17.9
2,EG03,Port Said,بورسعيد,1.42,16.9,10.8,32.3,1.56,7.9,33.9,33.8,18.0
3,EG04,Suez,السويس,1.39,14.8,13.4,29.4,0.96,8.0,40.5,30.1,4.4
4,EG11,Damietta,دمياط,1.31,24.6,5.1,33.3,3.73,7.2,35.4,31.3,70.0
5,EG12,Dakahlia,الدقهلية,1.30,20.3,5.9,36.4,3.42,7.1,36.6,26.9,51.9
6,EG13,Sharkia,الشرقية,1.33,20.6,6.1,29.7,2.78,7.4,37.9,32.4,35.6
7,EG14,Kalyoubia,القليوبية,1.33,17.8,9.9,29.7,3.44,7.3,42.4,27.9,46.0
8,EG15,Kafr El-Shikh,كفر الشيخ,1.33,20.4,6.0,28.9,4.15,7.1,37.0,34.1,64.8
9,EG16,Gharbia,الغربية,1.28,19.3,6.2,38.2,2.69,7.8,36.0,25.8,36.0

تجارة

In [28]:
import pandas as pd
import zipfile

zip_path = r"C:\Users\A-FF-L1-D06\Desktop\ملف المشروع\04_Trade_التجارة-20260825T061427Z-1-001.zip"

file_inside_zip = "04_Trade_التجارة/01_egypt_imports_by_partner.csv"

with zipfile.ZipFile(zip_path, 'r') as z:
    df_trade = pd.read_csv(
        z.open(file_inside_zip),
        encoding="utf-8-sig"
    )

print("Data loaded successfully ")
print("Shape:", df_trade.shape)

display(df_trade.head())

Data loaded successfully
Shape: (2755, 10)

,period,hs4,cmdCode,cmdDesc,partnerCode,partnerDesc,is_world,cifvalue,netWgt,qty
0,2015,1211,1211,Plants and parts of plants (including seeds an...,0,World,True,1.208312e+07,2385787.468,2385787.468
1,2015,1211,1211,Plants and parts of plants (including seeds an...,4,Afghanistan,False,3.770447e+05,76104.546,76104.546
2,2015,1211,1211,Plants and parts of plants (including seeds an...,8,Albania,False,6.632083e+05,133865.198,133865.198
3,2015,1211,1211,Plants and parts of plants (including seeds an...,31,Azerbaijan,False,1.186253e+05,23943.919,23943.919
4,2015,1211,1211,Plants and parts of plants (including seeds an...,56,Belgium,False,1.486821e+04,3001.072,3001.072

In [29]:
print("\nColumns:")
print(df_trade.columns.tolist())

Columns:
['period', 'hs4', 'cmdCode', 'cmdDesc', 'partnerCode', 'partnerDesc', 'is_world', 'cifvalue', 'netWgt', 'qty']

In [30]:
print("\nData Types:")
print(df_trade.dtypes)

Data Types:
period           int64
hs4              int64
cmdCode          int64
cmdDesc            str
partnerCode      int64
partnerDesc        str
is_world          bool
cifvalue       float64
netWgt         float64
qty            float64
dtype: object

In [31]:
print("\nMissing Values:")
print(df_trade.isna().sum())

Missing Values:
period           0
hs4              0
cmdCode          0
cmdDesc          0
partnerCode      0
partnerDesc      0
is_world         0
cifvalue         0
netWgt         656
qty              0
dtype: int64

In [32]:
numeric_cols = df_trade.select_dtypes(include="number").columns

In [33]:
print("\nZero Values:")
print((df_trade[numeric_cols] == 0).sum())

Zero Values:
period           0
hs4              0
cmdCode          0
partnerCode     99
cifvalue         0
netWgt         236
qty            892
dtype: int64

In [34]:
print("\nDuplicate Rows:")
print(df_trade.duplicated().sum())

Duplicate Rows:
0

In [35]:
print("\nNegative Values:")
print((df_trade[numeric_cols] < 0).sum())

Negative Values:
period         0
hs4            0
cmdCode        0
partnerCode    0
cifvalue       0
netWgt         0
qty            0
dtype: int64

In [36]:
file_inside_zip = "04_Trade_التجارة/02_egypt_imports_totals.csv"

with zipfile.ZipFile(zip_path, 'r') as z:
    df_trade_total = pd.read_csv(
        z.open(file_inside_zip),
        encoding="utf-8-sig"
    )

display(df_trade_total.head())

    hs4  period           usd
0  1211    2015  1.208312e+07
1  1211    2016  8.907567e+06
2  1211    2017  7.106108e+06
3  1211    2018  1.166731e+07
4  1211    2019  1.146254e+07

In [37]:
print(df_trade.shape)
print(df_trade.columns.tolist())
print(df_trade.isna().sum())

(2755, 10)
['period', 'hs4', 'cmdCode', 'cmdDesc', 'partnerCode', 'partnerDesc', 'is_world', 'cifvalue', 'netWgt', 'qty']
period           0
hs4              0
cmdCode          0
cmdDesc          0
partnerCode      0
partnerDesc      0
is_world         0
cifvalue         0
netWgt         656
qty              0
dtype: int64

In [38]:
print(df_trade.dtypes)

period           int64
hs4              int64
cmdCode          int64
cmdDesc            str
partnerCode      int64
partnerDesc        str
is_world          bool
cifvalue       float64
netWgt         float64
qty            float64
dtype: object

In [39]:
print("Duplicate Rows:", df_trade.duplicated().sum())

Duplicate Rows: 0

In [40]:
numeric_cols = df_trade.select_dtypes(include="number").columns

print("Zero Values:")
print((df_trade[numeric_cols] == 0).sum())

Zero Values:
period           0
hs4              0
cmdCode          0
partnerCode     99
cifvalue         0
netWgt         236
qty            892
dtype: int64

In [41]:
print("Negative Values:")
print((df_trade[numeric_cols] < 0).sum())

Negative Values:
period         0
hs4            0
cmdCode        0
partnerCode    0
cifvalue       0
netWgt         0
qty            0
dtype: int64

In [42]:
print("Number of Periods:", df_trade["period"].nunique())
print("Number of Products:", df_trade["cmdCode"].nunique())
print("Number of Partners:", df_trade["partnerCode"].nunique())

Number of Periods: 11
Number of Products: 9
Number of Partners: 139

In [43]:
print(df_trade["is_world"].value_counts(dropna=False))

is_world
False    2656
True       99
Name: count, dtype: int64

In [44]:
print("Missing netWgt:", df_trade["netWgt"].isna().sum())
print("Zero netWgt:", (df_trade["netWgt"] == 0).sum())
print("Negative netWgt:", (df_trade["netWgt"] < 0).sum())

Missing netWgt: 656
Zero netWgt: 236
Negative netWgt: 0

In [45]:
text_cols = df_trade.select_dtypes(include="object").columns

for col in text_cols:
    df_trade[col] = df_trade[col].astype("string").str.strip()

C:\Users\A-FF-L1-D06\AppData\Local\Temp\ipykernel_10400\1187503201.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_cols = df_trade.select_dtypes(include="object").columns

In [46]:
numeric_cols = [
    "period",
    "hs4",
    "cmdCode",
    "partnerCode",
    "cifvalue",
    "netWgt",
    "qty"
]

for col in numeric_cols:
    df_trade[col] = pd.to_numeric(df_trade[col], errors="coerce")

In [47]:
df_trade = df_trade.drop_duplicates()

In [48]:
print(df_trade.isna().sum())

period           0
hs4              0
cmdCode          0
cmdDesc          0
partnerCode      0
partnerDesc      0
is_world         0
cifvalue         0
netWgt         656
qty              0
dtype: int64

In [49]:
trade_cleaned = df_trade.copy()

In [50]:
output_path = r"C:\Users\A-FF-L1-D06\Desktop\ملف المشروع\Trade_Cleaned.csv"

trade_cleaned.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Trade file saved successfully ")

Trade file saved successfully

In [51]:
# 1. Check data types
print("Data Types:")
print(df_trade.dtypes)

# 2. Check duplicates
print("\nDuplicate Rows:")
print(df_trade.duplicated().sum())

# 3. Check zero values
numeric_cols = df_trade.select_dtypes(include="number").columns

print("\nZero Values:")
print((df_trade[numeric_cols] == 0).sum())

# 4. Check negative values
print("\nNegative Values:")
print((df_trade[numeric_cols] < 0).sum())

# 5. Unique periods
print("\nPeriods:")
print(df_trade["period"].unique())

# 6. Unique is_world values
print("\nis_world:")
print(df_trade["is_world"].value_counts(dropna=False))

# 7. Number of products
print("\nNumber of Products:")
print(df_trade["cmdCode"].nunique())

# 8. Number of partners
print("\nNumber of Partners:")
print(df_trade["partnerCode"].nunique())

# 9. Basic statistics
print("\nStatistics:")
print(df_trade[["cifvalue", "netWgt", "qty"]].describe())

Data Types:
period           int64
hs4              int64
cmdCode          int64
cmdDesc         string
partnerCode      int64
partnerDesc     string
is_world          bool
cifvalue       float64
netWgt         float64
qty            float64
dtype: object

Duplicate Rows:
0

Zero Values:
period           0
hs4              0
cmdCode          0
partnerCode     99
cifvalue         0
netWgt         236
qty            892
dtype: int64

Negative Values:
period         0
hs4            0
cmdCode        0
partnerCode    0
cifvalue       0
netWgt         0
qty            0
dtype: int64

Periods:
[2015 2016 2017 2018 2019 2020 2021 2022 2023 2024 2025]

is_world:
is_world
False    2656
True       99
Name: count, dtype: int64

Number of Products:
9

Number of Partners:
139

Statistics:
           cifvalue        netWgt           qty
count  2.755000e+03  2.099000e+03  2.755000e+03
mean   2.149557e+07  1.419355e+05  1.081389e+05
std    1.706040e+08  5.192320e+05  4.572079e+05
min    6.209000e+00  0.000000e+00  0.000000e+00
25%    1.785068e+04  1.519135e+02  0.000000e+00
50%    2.417789e+05  5.231907e+03  6.706810e+02
75%    1.943714e+06  6.097842e+04  3.172646e+04
max    3.300908e+09  7.928036e+06  7.928036e+06

In [52]:
print(
    df_trade.groupby("is_world")["partnerCode"]
    .agg(["count", "min", "max"])
)

          count  min  max
is_world
False      2656    4  899
True         99    0    0

In [53]:
print(
    df_trade[df_trade["is_world"] == True][
        ["period", "partnerCode", "partnerDesc", "cifvalue", "netWgt", "qty"]
    ].head(20)
)

     period  partnerCode partnerDesc      cifvalue       netWgt          qty
0      2015            0       World  1.208312e+07  2385787.468  2385787.468
39     2016            0       World  8.907567e+06  1761112.366  1761112.366
70     2017            0       World  7.106108e+06  1430448.143  1430448.143
101    2018            0       World  1.166731e+07  2105588.527  2105588.527
139    2019            0       World  1.146254e+07  2152122.249  2152122.249
177    2020            0       World  9.720251e+06  1792564.525  1792564.525
218    2021            0       World  1.345168e+07  2376255.675  2376255.675
258    2022            0       World  9.881031e+06  1594587.531  1594587.531
292    2023            0       World  1.224964e+07  1901813.523  1901813.523
334    2024            0       World  1.891112e+07  2870800.863  2870800.863
373    2025            0       World  1.645854e+07          NaN        0.000
408    2015            0       World  1.831740e+07  1330157.885  1330157.885
437    2016            0       World  1.869937e+07  1333543.555  1333543.555
459    2017            0       World  1.359769e+07   999866.104   999866.104
484    2018            0       World  1.619248e+07          NaN        0.000
509    2019            0       World  1.651346e+07          NaN        0.000
537    2020            0       World  1.889635e+07  1380513.112  1380513.112
565    2021            0       World  1.791318e+07  1318418.651  1318418.651
595    2022            0       World  2.555369e+07  1554567.333  1554567.333
624    2023            0       World  2.279322e+07          NaN        0.000

In [54]:
print("partnerCode = 0:")
display(df_trade[df_trade["partnerCode"] == 0])

print("qty = 0:")
display(df_trade[df_trade["qty"] == 0].head(20))

print("netWgt = 0:")
display(df_trade[df_trade["netWgt"] == 0].head(20))

partnerCode = 0:

,period,hs4,cmdCode,cmdDesc,partnerCode,partnerDesc,is_world,cifvalue,netWgt,qty
0,2015,1211,1211,Plants and parts of plants (including seeds an...,0,World,True,1.208312e+07,2385787.468,2385787.468
39,2016,1211,1211,Plants and parts of plants (including seeds an...,0,World,True,8.907567e+06,1761112.366,1761112.366
70,2017,1211,1211,Plants and parts of plants (including seeds an...,0,World,True,7.106108e+06,1430448.143,1430448.143
101,2018,1211,1211,Plants and parts of plants (including seeds an...,0,World,True,1.166731e+07,2105588.527,2105588.527
139,2019,1211,1211,Plants and parts of plants (including seeds an...,0,World,True,1.146254e+07,2152122.249,2152122.249
...,...,...,...,...,...,...,...,...,...,...
2530,2021,3301,3301,"Oils; essential (concretes, absolutes); concen...",0,World,True,1.498578e+07,NaN,0.000
2578,2022,3301,3301,"Oils; essential (concretes, absolutes); concen...",0,World,True,1.890341e+07,586465.667,586465.667
2630,2023,3301,3301,"Oils; essential (concretes, absolutes); concen...",0,World,True,9.715043e+06,NaN,0.000
2674,2024,3301,3301,"Oils; essential (concretes, absolutes); concen...",0,World,True,1.390910e+07,NaN,0.000
2715,2025,3301,3301,"Oils; essential (concretes, absolutes); concen...",0,World,True,1.296596e+07,534554.157,534554.157

qty = 0:

,period,hs4,cmdCode,cmdDesc,partnerCode,partnerDesc,is_world,cifvalue,netWgt,qty
373,2025,1211,1211,Plants and parts of plants (including seeds an...,0,World,True,1.645854e+07,NaN,0.0
374,2025,1211,1211,Plants and parts of plants (including seeds an...,4,Afghanistan,False,6.958094e+05,NaN,0.0
375,2025,1211,1211,Plants and parts of plants (including seeds an...,8,Albania,False,1.279500e+05,NaN,0.0
376,2025,1211,1211,Plants and parts of plants (including seeds an...,76,Brazil,False,1.573500e+01,NaN,0.0
377,2025,1211,1211,Plants and parts of plants (including seeds an...,100,Bulgaria,False,1.001000e+01,NaN,0.0
378,2025,1211,1211,Plants and parts of plants (including seeds an...,124,Canada,False,1.518100e+01,NaN,0.0
379,2025,1211,1211,Plants and parts of plants (including seeds an...,156,China,False,7.313644e+05,NaN,0.0
380,2025,1211,1211,Plants and parts of plants (including seeds an...,191,Croatia,False,8.771392e+03,NaN,0.0
381,2025,1211,1211,Plants and parts of plants (including seeds an...,251,France,False,1.213420e+02,NaN,0.0
382,2025,1211,1211,Plants and parts of plants (including seeds an...,276,Germany,False,4.085606e+04,NaN,0.0
383,2025,1211,1211,Plants and parts of plants (including seeds an...,360,Indonesia,False,3.391053e+05,NaN,0.0
384,2025,1211,1211,Plants and parts of plants (including seeds an...,368,Iraq,False,6.416781e+05,NaN,0.0
385,2025,1211,1211,Plants and parts of plants (including seeds an...,380,Italy,False,1.230000e+02,NaN,0.0
386,2025,1211,1211,Plants and parts of plants (including seeds an...,398,Kazakhstan,False,6.188161e+04,NaN,0.0
387,2025,1211,1211,Plants and parts of plants (including seeds an...,400,Jordan,False,3.617213e+04,NaN,0.0
388,2025,1211,1211,Plants and parts of plants (including seeds an...,422,Lebanon,False,3.668374e+04,NaN,0.0
389,2025,1211,1211,Plants and parts of plants (including seeds an...,504,Morocco,False,2.834456e+03,NaN,0.0
390,2025,1211,1211,Plants and parts of plants (including seeds an...,528,Netherlands,False,1.274302e+03,NaN,0.0
391,2025,1211,1211,Plants and parts of plants (including seeds an...,566,Nigeria,False,6.249412e+06,NaN,0.0
392,2025,1211,1211,Plants and parts of plants (including seeds an...,586,Pakistan,False,1.252672e+06,NaN,0.0

netWgt = 0:

,period,hs4,cmdCode,cmdDesc,partnerCode,partnerDesc,is_world,cifvalue,netWgt,qty
728,2015,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,0,World,True,3.541272e+07,0.0,0.0
729,2015,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,56,Belgium,False,3.191830e+04,0.0,0.0
738,2015,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,504,Morocco,False,6.368693e+04,0.0,0.0
739,2015,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,528,Netherlands,False,3.077378e+04,0.0,0.0
741,2015,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,642,Romania,False,1.349863e+05,0.0,0.0
746,2015,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,752,Sweden,False,5.728553e+05,0.0,0.0
750,2016,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,0,World,True,3.626483e+07,0.0,0.0
755,2016,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,360,Indonesia,False,2.071070e+02,0.0,0.0
757,2016,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,392,Japan,False,2.896359e+03,0.0,0.0
759,2016,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,504,Morocco,False,1.180558e+05,0.0,0.0
765,2016,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,752,Sweden,False,3.933070e+05,0.0,0.0
770,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,0,World,True,2.478005e+07,0.0,0.0
776,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,300,Greece,False,8.288039e+04,0.0,0.0
778,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,392,Japan,False,5.265757e+03,0.0,0.0
779,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,410,Rep. of Korea,False,1.351117e+05,0.0,0.0
781,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,504,Morocco,False,3.000941e+05,0.0,0.0
783,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,642,Romania,False,5.285050e+04,0.0,0.0
786,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,702,Singapore,False,8.855512e+03,0.0,0.0
787,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,724,Spain,False,1.310471e+06,0.0,0.0
788,2017,2932,2932,Heterocyclic compounds with oxygen hetero-atom...,752,Sweden,False,4.504997e+05,0.0,0.0

In [55]:
print("Partners:")
display(
    df_trade[["partnerCode", "partnerDesc"]]
    .drop_duplicates()
    .sort_values("partnerCode")
)

print("Products:")
display(
    df_trade[["cmdCode", "cmdDesc"]]
    .drop_duplicates()
    .sort_values("cmdCode")
)

Partners:

      partnerCode   partnerDesc
0               0         World
1               4   Afghanistan
2               8       Albania
1854           12       Algeria
3              31    Azerbaijan
...           ...           ...
136           854  Burkina Faso
36            858       Uruguay
37            860    Uzbekistan
1904          887         Yemen
38            899    Areas, nes

[139 rows x 2 columns]

Products:

      cmdCode                                            cmdDesc
0        1211  Plants and parts of plants (including seeds an...
258      1211  Plants and parts of plants (including seeds an...
408      1302  Vegetable saps and extracts; pectic substances...
728      2932  Heterocyclic compounds with oxygen hetero-atom...
993      2937  Hormones, prostaglandins, thromboxanes and leu...
1177     2938  Glycosides, natural or reproduced by synthesis...
1289     2939  Alkaloids, vegetable; natural or reproduced by...
1406     2939  Alkaloids; natural or reproduced by synthesis,...
1479     3003  Medicaments; (not goods of heading no. 3002, 3...
1681     3004  Medicaments; (not goods of heading no. 3002, 3...
2316     3301  Oils; essential (concretes, absolutes); concen...

In [56]:
print("Zero qty:")
display(df_trade[df_trade["qty"] == 0][
    ["period", "cmdCode", "cmdDesc", "partnerDesc", "cifvalue", "netWgt", "qty"]
].head(20))

print("\nZero netWgt:")
display(df_trade[df_trade["netWgt"] == 0][
    ["period", "cmdCode", "cmdDesc", "partnerDesc", "cifvalue", "netWgt", "qty"]
].head(20))

Zero qty:

,period,cmdCode,cmdDesc,partnerDesc,cifvalue,netWgt,qty
373,2025,1211,Plants and parts of plants (including seeds an...,World,1.645854e+07,NaN,0.0
374,2025,1211,Plants and parts of plants (including seeds an...,Afghanistan,6.958094e+05,NaN,0.0
375,2025,1211,Plants and parts of plants (including seeds an...,Albania,1.279500e+05,NaN,0.0
376,2025,1211,Plants and parts of plants (including seeds an...,Brazil,1.573500e+01,NaN,0.0
377,2025,1211,Plants and parts of plants (including seeds an...,Bulgaria,1.001000e+01,NaN,0.0
378,2025,1211,Plants and parts of plants (including seeds an...,Canada,1.518100e+01,NaN,0.0
379,2025,1211,Plants and parts of plants (including seeds an...,China,7.313644e+05,NaN,0.0
380,2025,1211,Plants and parts of plants (including seeds an...,Croatia,8.771392e+03,NaN,0.0
381,2025,1211,Plants and parts of plants (including seeds an...,France,1.213420e+02,NaN,0.0
382,2025,1211,Plants and parts of plants (including seeds an...,Germany,4.085606e+04,NaN,0.0
383,2025,1211,Plants and parts of plants (including seeds an...,Indonesia,3.391053e+05,NaN,0.0
384,2025,1211,Plants and parts of plants (including seeds an...,Iraq,6.416781e+05,NaN,0.0
385,2025,1211,Plants and parts of plants (including seeds an...,Italy,1.230000e+02,NaN,0.0
386,2025,1211,Plants and parts of plants (including seeds an...,Kazakhstan,6.188161e+04,NaN,0.0
387,2025,1211,Plants and parts of plants (including seeds an...,Jordan,3.617213e+04,NaN,0.0
388,2025,1211,Plants and parts of plants (including seeds an...,Lebanon,3.668374e+04,NaN,0.0
389,2025,1211,Plants and parts of plants (including seeds an...,Morocco,2.834456e+03,NaN,0.0
390,2025,1211,Plants and parts of plants (including seeds an...,Netherlands,1.274302e+03,NaN,0.0
391,2025,1211,Plants and parts of plants (including seeds an...,Nigeria,6.249412e+06,NaN,0.0
392,2025,1211,Plants and parts of plants (including seeds an...,Pakistan,1.252672e+06,NaN,0.0

Zero netWgt:

,period,cmdCode,cmdDesc,partnerDesc,cifvalue,netWgt,qty
728,2015,2932,Heterocyclic compounds with oxygen hetero-atom...,World,3.541272e+07,0.0,0.0
729,2015,2932,Heterocyclic compounds with oxygen hetero-atom...,Belgium,3.191830e+04,0.0,0.0
738,2015,2932,Heterocyclic compounds with oxygen hetero-atom...,Morocco,6.368693e+04,0.0,0.0
739,2015,2932,Heterocyclic compounds with oxygen hetero-atom...,Netherlands,3.077378e+04,0.0,0.0
741,2015,2932,Heterocyclic compounds with oxygen hetero-atom...,Romania,1.349863e+05,0.0,0.0
746,2015,2932,Heterocyclic compounds with oxygen hetero-atom...,Sweden,5.728553e+05,0.0,0.0
750,2016,2932,Heterocyclic compounds with oxygen hetero-atom...,World,3.626483e+07,0.0,0.0
755,2016,2932,Heterocyclic compounds with oxygen hetero-atom...,Indonesia,2.071070e+02,0.0,0.0
757,2016,2932,Heterocyclic compounds with oxygen hetero-atom...,Japan,2.896359e+03,0.0,0.0
759,2016,2932,Heterocyclic compounds with oxygen hetero-atom...,Morocco,1.180558e+05,0.0,0.0
765,2016,2932,Heterocyclic compounds with oxygen hetero-atom...,Sweden,3.933070e+05,0.0,0.0
770,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,World,2.478005e+07,0.0,0.0
776,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,Greece,8.288039e+04,0.0,0.0
778,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,Japan,5.265757e+03,0.0,0.0
779,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,Rep. of Korea,1.351117e+05,0.0,0.0
781,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,Morocco,3.000941e+05,0.0,0.0
783,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,Romania,5.285050e+04,0.0,0.0
786,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,Singapore,8.855512e+03,0.0,0.0
787,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,Spain,1.310471e+06,0.0,0.0
788,2017,2932,Heterocyclic compounds with oxygen hetero-atom...,Sweden,4.504997e+05,0.0,0.0

In [57]:
print((df_trade["netWgt"] == 0).sum())

236

In [58]:
print("Missing netWgt:", df_trade["netWgt"].isna().sum())
print("Zero qty:", (df_trade["qty"] == 0).sum())

Missing netWgt: 656
Zero qty: 892

In [59]:
print("qty = 0 and netWgt = 0:")
print(
    (
        (df_trade["qty"] == 0) &
        (df_trade["netWgt"] == 0)
    ).sum()
)

print("\nqty = 0 and netWgt is missing:")
print(
    (
        (df_trade["qty"] == 0) &
        (df_trade["netWgt"].isna())
    ).sum()
)

print("\nqty > 0 and netWgt = 0:")
print(
    (
        (df_trade["qty"] > 0) &
        (df_trade["netWgt"] == 0)
    ).sum()
)

print("\nqty = 0 and netWgt > 0:")
print(
    (
        (df_trade["qty"] == 0) &
        (df_trade["netWgt"] > 0)
    ).sum()
)

qty = 0 and netWgt = 0:
236

qty = 0 and netWgt is missing:
656

qty > 0 and netWgt = 0:
0

qty = 0 and netWgt > 0:
0

In [60]:
# Clean text columns
text_cols = df_trade.select_dtypes(include="object").columns

for col in text_cols:
    df_trade[col] = df_trade[col].astype("string").str.strip()

# Remove duplicate rows
df_trade = df_trade.drop_duplicates()

# Final checks
print("Final Shape:", df_trade.shape)
print("\nMissing Values:")
print(df_trade.isna().sum())

print("\nDuplicate Rows:")
print(df_trade.duplicated().sum())

Final Shape: (2755, 10)

Missing Values:
period           0
hs4              0
cmdCode          0
cmdDesc          0
partnerCode      0
partnerDesc      0
is_world         0
cifvalue         0
netWgt         656
qty              0
dtype: int64

Duplicate Rows:
0

In [61]:
output_path = r"C:\Users\A-FF-L1-D06\Desktop\ملف المشروع\Trade_Cleaned.csv"

df_trade.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Trade_Cleaned.csv saved successfully ")

Trade_Cleaned.csv saved successfully

In [62]:
print(df_trade.columns.tolist())
display(df_trade.head(10))

['period', 'hs4', 'cmdCode', 'cmdDesc', 'partnerCode', 'partnerDesc', 'is_world', 'cifvalue', 'netWgt', 'qty']

,period,hs4,cmdCode,cmdDesc,partnerCode,partnerDesc,is_world,cifvalue,netWgt,qty
0,2015,1211,1211,Plants and parts of plants (including seeds an...,0,World,True,1.208312e+07,2385787.468,2385787.468
1,2015,1211,1211,Plants and parts of plants (including seeds an...,4,Afghanistan,False,3.770447e+05,76104.546,76104.546
2,2015,1211,1211,Plants and parts of plants (including seeds an...,8,Albania,False,6.632083e+05,133865.198,133865.198
3,2015,1211,1211,Plants and parts of plants (including seeds an...,31,Azerbaijan,False,1.186253e+05,23943.919,23943.919
4,2015,1211,1211,Plants and parts of plants (including seeds an...,56,Belgium,False,1.486821e+04,3001.072,3001.072
5,2015,1211,1211,Plants and parts of plants (including seeds an...,100,Bulgaria,False,1.122902e+05,22665.201,22665.201
6,2015,1211,1211,Plants and parts of plants (including seeds an...,124,Canada,False,5.768763e+03,1164.395,1164.395
7,2015,1211,1211,Plants and parts of plants (including seeds an...,156,China,False,6.167504e+05,103982.571,103982.571
8,2015,1211,1211,Plants and parts of plants (including seeds an...,191,Croatia,False,4.745220e+02,95.780,95.780
9,2015,1211,1211,Plants and parts of plants (including seeds an...,196,Cyprus,False,2.830782e+04,5713.788,5713.788

In [63]:
print("Products:", df_trade["cmdDesc"].nunique())
print("Partners:", df_trade["partnerDesc"].nunique())
print("Years:", df_trade["period"].nunique())

print("\nProducts:")
display(df_trade[["cmdCode", "cmdDesc"]].drop_duplicates())

print("\nPartners:")
display(df_trade[["partnerCode", "partnerDesc"]].drop_duplicates().head(20))

Products: 11
Partners: 139
Years: 11

Products:

      cmdCode                                            cmdDesc
0        1211  Plants and parts of plants (including seeds an...
258      1211  Plants and parts of plants (including seeds an...
408      1302  Vegetable saps and extracts; pectic substances...
728      2932  Heterocyclic compounds with oxygen hetero-atom...
993      2937  Hormones, prostaglandins, thromboxanes and leu...
1177     2938  Glycosides, natural or reproduced by synthesis...
1289     2939  Alkaloids, vegetable; natural or reproduced by...
1406     2939  Alkaloids; natural or reproduced by synthesis,...
1479     3003  Medicaments; (not goods of heading no. 3002, 3...
1681     3004  Medicaments; (not goods of heading no. 3002, 3...
2316     3301  Oils; essential (concretes, absolutes); concen...

Partners:

    partnerCode  partnerDesc
0             0        World
1             4  Afghanistan
2             8      Albania
3            31   Azerbaijan
4            56      Belgium
5           100     Bulgaria
6           124       Canada
7           156        China
8           191      Croatia
9           196       Cyprus
10          251       France
11          268      Georgia
12          276      Germany
13          300       Greece
14          320    Guatemala
15          360    Indonesia
16          364         Iran
17          388      Jamaica
18          422      Lebanon
19          504      Morocco

الجغرافيا

In [67]:
import pandas as pd

In [71]:
r"C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\07_Geography_الجغرافيا-20260825T062325Z-1-001.zip"

'C:\\Users\\A-FF-L1-D06\\Downloads\\ملف المشروع\\07_Geography_الجغرافيا-20260825T062325Z-1-001.zip'

In [73]:
import zipfile
import os

zip_path = r"C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\07_Geography_الجغرافيا-20260825T062325Z-1-001.zip"

extract_path = r"C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print("تم فك ضغط الملف بنجاح ")

تم فك ضغط الملف بنجاح

In [74]:
for root, dirs, files in os.walk(extract_path):
    for file in files:
        print(os.path.join(root, file))

C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\01_governorates.csv
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\Data_Dictionary_Geography.xlsx
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\README.txt
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\README_اقرأني.txt
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin0.cpg
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin0.dbf
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin0.prj
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin0.shp
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin0.shx
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin1.cpg
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin1.dbf
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin1.prj
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin1.shp
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin1.shx
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\egy_admin_attributes.xlsx
C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\shapefiles\README_MAPPING.txt

In [75]:
import pandas as pd

file_path = r"C:\Users\A-FF-L1-D06\Downloads\ملف المشروع\Geography\07_Geography_الجغرافيا\01_governorates.csv"

df_geo = pd.read_csv(file_path)

display(df_geo.head(10))

  adm1_pcode         gov_en      gov_ar        lat        lon    area_sqkm
0       EG01          Cairo     القاهرة  29.966496  31.572883  2888.813336
1       EG02     Alexandria  الاسكندرية  30.798175  29.707656  2510.046983
2       EG03      Port Said     بورسعيد  31.066977  32.429971   980.292944
3       EG04           Suez      السويس  29.621884  32.121394  9358.101239
4       EG11       Damietta       دمياط  31.393679  31.628311   752.890264
5       EG12       Dakahlia    الدقهلية  30.966366  31.468504  3491.662231
6       EG13        Sharkia     الشرقية  30.649608  31.772194  5333.953004
7       EG14      Kalyoubia   القليوبية  30.360127  31.209127  1132.103263
8       EG15  Kafr El-Shikh   كفر الشيخ  31.309825  30.901371  3265.057729
9       EG16        Gharbia     الغربية  30.871644  31.016873  1973.915130

In [76]:
print("Shape:", df_geo.shape)

print("\nColumns:")
print(df_geo.columns.tolist())

print("\nData Types:")
print(df_geo.dtypes)

Shape: (27, 6)

Columns:
['adm1_pcode', 'gov_en', 'gov_ar', 'lat', 'lon', 'area_sqkm']

Data Types:
adm1_pcode        str
gov_en            str
gov_ar            str
lat           float64
lon           float64
area_sqkm     float64
dtype: object

In [77]:
print("Missing Values:")
display(df_geo.isnull().sum())

print("\nDuplicate Rows:")
print(df_geo.duplicated().sum())

Missing Values:

adm1_pcode    0
gov_en        0
gov_ar        0
lat           0
lon           0
area_sqkm     0
dtype: int64

Duplicate Rows:
0

In [79]:
df_geo.columns = (
    df_geo.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

print(df_geo.columns)

Index(['adm1_pcode', 'gov_en', 'gov_ar', 'lat', 'lon', 'area_sqkm'], dtype='str')

In [80]:
text_columns = [
    "adm1_pcode",
    "gov_en",
    "gov_ar"
]

for col in text_columns:
    df_geo[col] = (
        df_geo[col]
        .astype(str)
        .str.strip()
    )

In [81]:
print(df_geo["gov_ar"].unique())

<StringArray>
[      'القاهرة',    'الاسكندرية',       'بورسعيد',        'السويس',
         'دمياط',      'الدقهلية',       'الشرقية',     'القليوبية',
     'كفر الشيخ',       'الغربية',      'المنوفية',       'البحيرة',
   'الإسماعيلية',        'الجيزة',      'بنى سويف',        'الفيوم',
        'المنيا',         'أسيوط',         'سوهاج',           'قنا',
         'أسوان',  'مدينة الأقصر',  'البحر الأحمر', 'الوادى الجديد',
         'مطروح',    'شمال سيناء',    'جنوب سيناء']
Length: 27, dtype: str

In [82]:
print(df_geo.dtypes)

adm1_pcode        str
gov_en            str
gov_ar            str
lat           float64
lon           float64
area_sqkm     float64
dtype: object

In [83]:
numeric_columns = [
    "lat",
    "lon",
    "area_sqkm"
]

for col in numeric_columns:
    df_geo[col] = pd.to_numeric(
        df_geo[col],
        errors="coerce"
    )

In [84]:
display(df_geo.isnull().sum())

adm1_pcode    0
gov_en        0
gov_ar        0
lat           0
lon           0
area_sqkm     0
dtype: int64

In [85]:
invalid_lat = df_geo[
    (df_geo["lat"] < -90) |
    (df_geo["lat"] > 90)
]

invalid_lon = df_geo[
    (df_geo["lon"] < -180) |
    (df_geo["lon"] > 180)
]

print("Invalid Latitude:", len(invalid_lat))
print("Invalid Longitude:", len(invalid_lon))

Invalid Latitude: 0
Invalid Longitude: 0

In [86]:
invalid_area = df_geo[
    df_geo["area_sqkm"] <= 0
]

print("Invalid Area:", len(invalid_area))

Invalid Area: 0

In [87]:
df_geo["lat"] = df_geo["lat"].round(6)

df_geo["lon"] = df_geo["lon"].round(6)

df_geo["area_sqkm"] = df_geo["area_sqkm"].round(2)

In [88]:
df_geo.to_csv(
    "Geography_Cleaned.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Geography_Cleaned.csv saved successfully")

Geography_Cleaned.csv saved successfully